### 결측 데이터

#### 결측치
* 누락되거나 문제가 있는 데이터를 의미한다
* 데이터 입력시 인코딩 또는 네트워크 문제, 공란 등의 이유로 무엇인지 판단하기 어려운 데이터
* 판다스에서는 결측값을 NaN(Not a Number)으로 표기하며 None, 공백도 결측치로 사용된다

#### 결측치 처리 방법
* 결측치 확인
* 결측치 대체 / 제거
* 결측치 반영 확인

#### 결측치 확인 함수
* isnull() : 결측치 True, 유효 데이터 False 반환
* notnull() : 결측치 False, 유효 데이터 True 반환

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data_set/2.데이터 클린징/nan.csv")
df

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [4]:
df.head(3)

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN

In [6]:
df.tail(3)

   data1  data2  data3  nan_1  nan_2
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [7]:
df.isnull() # 결측 데이터 True

   data1  data2  data3  nan_1  nan_2
0  False  False  False  False   True
1  False  False  False   True   True
2  False  False  False  False   True
3  False  False  False   True   True
4  False  False  False  False   True
5  False  False  False   True  False

In [8]:
df.isnull().sum()

data1    0
data2    0
data3    0
nan_1    3
nan_2    5
dtype: int64

In [9]:
df.shape

(6, 5)

In [10]:
df.notnull() # 결측치 False

   data1  data2  data3  nan_1  nan_2
0   True   True   True   True  False
1   True   True   True  False  False
2   True   True   True   True  False
3   True   True   True  False  False
4   True   True   True   True  False
5   True   True   True  False   True

In [11]:
df.notnull().sum()

data1    6
data2    6
data3    6
nan_1    3
nan_2    1
dtype: int64

In [12]:
df

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [13]:
df.dropna() # 결측치 행 전부 삭제, 기본 axis = 0

Empty DataFrame
Columns: [data1, data2, data3, nan_1, nan_2]
Index: []

In [14]:
df.dropna(axis=0)

Empty DataFrame
Columns: [data1, data2, data3, nan_1, nan_2]
Index: []

In [15]:
df.dropna(axis=1)

   data1  data2  data3
0      0      1      2
1      3      4      2
2      3      4      8
3      9     10     11
4     12     10     14
5     15     16     17

In [18]:
df['nan_1']
df['nan_1'].isnull()

0    False
1     True
2    False
3     True
4    False
5     True
Name: nan_1, dtype: bool

In [19]:
df[df['nan_1'].isnull()]

   data1  data2  data3  nan_1  nan_2
1      3      4      2    NaN    NaN
3      9     10     11    NaN    NaN
5     15     16     17    NaN    1.0

In [20]:
df[df['nan_1'].notnull()]

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
2      3      4      8    2.4    NaN
4     12     10     14    1.2    NaN

In [21]:
df.loc[df['nan_1'].notnull()]

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
2      3      4      8    2.4    NaN
4     12     10     14    1.2    NaN

In [22]:
df.fillna(value=100)

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7  100.0
1      3      4      2  100.0  100.0
2      3      4      8    2.4  100.0
3      9     10     11  100.0  100.0
4     12     10     14    1.2  100.0
5     15     16     17  100.0    1.0

In [23]:
df.fillna(0)

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    0.0
1      3      4      2    0.0    0.0
2      3      4      8    2.4    0.0
3      9     10     11    0.0    0.0
4     12     10     14    1.2    0.0
5     15     16     17    0.0    1.0

In [24]:
df.mean()

data1    7.000000
data2    7.500000
data3    9.000000
nan_1    1.766667
nan_2    1.000000
dtype: float64

In [25]:
df.fillna(df.mean())

   data1  data2  data3     nan_1  nan_2
0      0      1      2  1.700000    1.0
1      3      4      2  1.766667    1.0
2      3      4      8  2.400000    1.0
3      9     10     11  1.766667    1.0
4     12     10     14  1.200000    1.0
5     15     16     17  1.766667    1.0

In [26]:
data = {
    'v1' : [12, 12, 17, 1, 3, 6, 6, 7, 10],
    'v2' : [1, 3, 6, 6, 6, 7, 7, 12, 12]
}

df_test = pd.DataFrame(data)
df_test

   v1  v2
0  12   1
1  12   3
2  17   6
3   1   6
4   3   6
5   6   7
6   6   7
7   7  12
8  10  12

In [27]:
df_test.mode() # 최빈값

   v1   v2
0   6  6.0
1  12  NaN

In [28]:
df_test.median() # 중앙값

v1    7.0
v2    6.0
dtype: float64

In [29]:
df_test['v1'].sort_values()

3     1
4     3
5     6
6     6
7     7
8    10
1    12
0    12
2    17
Name: v1, dtype: int64

In [30]:
df_test['v1'].value_counts()

v1
12    2
6     2
17    1
1     1
3     1
7     1
10    1
Name: count, dtype: int64

In [31]:
df_test['v2'].mode()

0    6
Name: v2, dtype: int64

In [32]:
df

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [33]:
df.median()

data1    6.0
data2    7.0
data3    9.5
nan_1    1.7
nan_2    1.0
dtype: float64

In [34]:
df.fillna( df.median() )

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    1.0
1      3      4      2    1.7    1.0
2      3      4      8    2.4    1.0
3      9     10     11    1.7    1.0
4     12     10     14    1.2    1.0
5     15     16     17    1.7    1.0

In [35]:
df.mode()

   data1  data2  data3  nan_1  nan_2
0    3.0    4.0    2.0    1.2    1.0
1    NaN   10.0    NaN    1.7    NaN
2    NaN    NaN    NaN    2.4    NaN

In [36]:
df.mode().loc[0]

data1    3.0
data2    4.0
data3    2.0
nan_1    1.2
nan_2    1.0
Name: 0, dtype: float64

In [37]:
df.fillna( df.mode().loc[0] )

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    1.0
1      3      4      2    1.2    1.0
2      3      4      8    2.4    1.0
3      9     10     11    1.2    1.0
4     12     10     14    1.2    1.0
5     15     16     17    1.2    1.0

In [38]:
df

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    NaN    NaN
2      3      4      8    2.4    NaN
3      9     10     11    NaN    NaN
4     12     10     14    1.2    NaN
5     15     16     17    NaN    1.0

In [39]:
df.ffill() # 처음부터 시작 -> nan 전 값으로 채움

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    NaN
1      3      4      2    1.7    NaN
2      3      4      8    2.4    NaN
3      9     10     11    2.4    NaN
4     12     10     14    1.2    NaN
5     15     16     17    1.2    1.0

In [40]:
df.bfill()  # 아래부터 시작 -> nan 전 값으로 채움

   data1  data2  data3  nan_1  nan_2
0      0      1      2    1.7    1.0
1      3      4      2    2.4    1.0
2      3      4      8    2.4    1.0
3      9     10     11    1.2    1.0
4     12     10     14    1.2    1.0
5     15     16     17    NaN    1.0

In [41]:
df['nan_1'].unique() # 데이터 프레임 자체로는 못 사용함

array([1.7, nan, 2.4, 1.2])

In [42]:
df['data2'].unique()

array([ 1,  4, 10, 16])