# Pandas
- 특정 데이터를 DataFrame 형식으로 처리

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [5]:
df['name']

0     Kim
1     Cho
2    Choi
3      jo
Name: name, dtype: str

In [6]:
df.age

0    20
1    30
2    40
3    50
Name: age, dtype: int64

In [7]:
df[["name", "age"]]

   name  age
0   Kim   20
1   Cho   30
2  Choi   40
3    jo   50

In [8]:
df[["name"]]

   name
0   Kim
1   Cho
2  Choi
3    jo

In [9]:
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [10]:
df[1:3]

   name  score grade  age
1   Cho   95.0     A   30
2  Choi   90.5     B   40

In [11]:
df.loc[1:3]

   name  score grade  age
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [12]:
df[1:3]['name'] # 복사본

1     Cho
2    Choi
Name: name, dtype: str

In [13]:
df.loc[1:3, 'name'] # 원본

1     Cho
2    Choi
3      jo
Name: name, dtype: str

In [14]:
df[1:3]['name'] = "aaaa"

C:\Users\user\AppData\Local\Temp\ipykernel_17972\1910646238.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[1:3]['name'] = "aaaa"

In [15]:
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [16]:
df.loc[1:3, 'name'] = 'aaaa'

In [17]:
df

   name  score grade  age
0   Kim  100.0     A   20
1  aaaa   95.0     A   30
2  aaaa   90.5     B   40
3  aaaa   85.7     B   50

In [30]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [31]:
df.loc[ : , 'name']

0     Kim
1     Cho
2    Choi
3      jo
Name: name, dtype: str

In [32]:
df.loc[:, ['name', 'age']]

   name  age
0   Kim   20
1   Cho   30
2  Choi   40
3    jo   50

In [33]:
df.loc[:]

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [34]:
df['grade'] == 'A'

0     True
1     True
2    False
3    False
Name: grade, dtype: bool

In [35]:
df.loc[ df['grade'] == 'A']

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [36]:
df.loc[ df['grade'] == 'A', 'grade'] = 'CCC'
df

   name  score grade  age
0   Kim  100.0   CCC   20
1   Cho   95.0   CCC   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [37]:
df.drop(2) # index 기준으로 drop

  name  score grade  age
0  Kim  100.0   CCC   20
1  Cho   95.0   CCC   30
3   jo   85.7     B   50

In [38]:
df

   name  score grade  age
0   Kim  100.0   CCC   20
1   Cho   95.0   CCC   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [39]:
df = df.drop(2)
df

  name  score grade  age
0  Kim  100.0   CCC   20
1  Cho   95.0   CCC   30
3   jo   85.7     B   50

In [40]:
df.drop(1, inplace = True) # 자기 자신에 적용
df

  name  score grade  age
0  Kim  100.0   CCC   20
3   jo   85.7     B   50

In [41]:
df.drop(0, axis=0, inplace=True) # 행
df

  name  score grade  age
3   jo   85.7     B   50

In [42]:
df.drop('name', axis=1, inplace=True) # 열
df

   score grade  age
3   85.7     B   50

In [43]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [44]:
df['score'] < 95

0    False
1    False
2     True
3     True
Name: score, dtype: bool

In [45]:
df[ df['score'] < 95 ]

   name  score grade  age
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [46]:
df.loc[ df['score'] < 95 ]

   name  score grade  age
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [47]:
df[ df['score'] < 95 ]['name']

2    Choi
3      jo
Name: name, dtype: str

In [48]:
df[ df['score'] < 95][ ['name', 'age'] ]

   name  age
2  Choi   40
3    jo   50

In [49]:
df.loc[ df['score'] < 95, ['name', 'age'] ]

   name  age
2  Choi   40
3    jo   50

In [50]:
df.columns

Index(['name', 'score', 'grade', 'age'], dtype='str')

In [51]:
df.values

array([['Kim', 100.0, 'A', 20],
       ['Cho', 95.0, 'A', 30],
       ['Choi', 90.5, 'B', 40],
       ['jo', 85.7, 'B', 50]], dtype=object)

In [53]:
df.dtypes

name         str
score    float64
grade        str
age        int64
dtype: object

In [54]:
df['grade']

0    A
1    A
2    B
3    B
Name: grade, dtype: str

In [55]:
df['grade'].isin(['A'])

0     True
1     True
2    False
3    False
Name: grade, dtype: bool

In [56]:
df[ df['grade'].isin(['A']) ]

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [57]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [58]:
index_name = ['김', '이', '박', '조']
df.index = index_name
df

   name  score grade  age
김   Kim  100.0     A   20
이   Cho   95.0     A   30
박  Choi   90.5     B   40
조    jo   85.7     B   50

In [59]:
df.index

Index(['김', '이', '박', '조'], dtype='str')

In [60]:
df[1:3]

   name  score grade  age
이   Cho   95.0     A   30
박  Choi   90.5     B   40

In [61]:
df['이':'조']

   name  score grade  age
이   Cho   95.0     A   30
박  Choi   90.5     B   40
조    jo   85.7     B   50