### 데이터 조회

In [12]:
# 1.Quiz.csv파일을 불러와 아래와 같이 표현하시오

   경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
0   39060    7313    3627     309     300     B
1   39896    6967    4168    1771     350     B
2   42005    6873    4088    1954     450     A
3   43621    6626    4424    2244     560     A
4   41702    8675    4606    3146    1300     A
5   41266   10622    4984    3945    2395     A
6   32427    9228    5570    5766    3786     C

In [2]:
import pandas as pd

df = pd.read_csv("../data_set/1.pandas/1.Quiz.csv")
df

   경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
0   39060    7313    3627     309     300     B
1   39896    6967    4168    1771     350     B
2   42005    6873    4088    1954     450     A
3   43621    6626    4424    2244     560     A
4   41702    8675    4606    3146    1300     A
5   41266   10622    4984    3945    2395     A
6   32427    9228    5570    5766    3786     C

In [13]:
# index설정
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']
df.index = index_list
df

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B
2012   39896    6967    4168    1771     350     B
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A
2016   41266   10622    4984    3945    2395     A
2017   32427    9228    5570    5766    3786     C

In [3]:
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']
df.index = index_list
df

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B
2012   39896    6967    4168    1771     350     B
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A
2016   41266   10622    4984    3945    2395     A
2017   32427    9228    5570    5766    3786     C

### 컬럼 조회

In [14]:
#컬럼들만 추출

Index(['경부선KTX', '호남선KTX', '경전선KTX', '전라선KTX', '동해선KTX', '경부선등급'], dtype='object')

In [4]:
df.columns

Index(['경부선KTX', '호남선KTX', '경전선KTX', '전라선KTX', '동해선KTX', '경부선등급'], dtype='str')

In [15]:
#경부선KTX 열만 조회

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선KTX, dtype: int64

In [5]:
df['경부선KTX']

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선KTX, dtype: int64

In [16]:
#경부선KTX, 호남선KTX 컬럼 조회

      경부선KTX  호남선KTX
2011   39060    7313
2012   39896    6967
2013   42005    6873
2014   43621    6626
2015   41702    8675
2016   41266   10622
2017   32427    9228

In [6]:
df[ ['경부선KTX', '호남선KTX'] ]

      경부선KTX  호남선KTX
2011   39060    7313
2012   39896    6967
2013   42005    6873
2014   43621    6626
2015   41702    8675
2016   41266   10622
2017   32427    9228

In [17]:
# 인덱싱 사용(loc사용 아님)행기준 조회, 2012~2015년도
# 인덱스 번호를 이용하세요

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2012   39896    6967    4168    1771     350     B
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A

In [8]:
df['2012':'2015']

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2012   39896    6967    4168    1771     350     B
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A

In [18]:
#행기준 조회, 2012~2015년도
# 해당 인덱스의 이름으로 조회하세요

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2012   39896    6967    4168    1771     350     B
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A

### loc를 이용한 조회

In [19]:
#loc 사용, 컬럼이 '경부선KTX' 의 모든행

      경부선KTX
2011   39060
2012   39896
2013   42005
2014   43621
2015   41702
2016   41266
2017   32427

In [15]:
df.loc[:, ['경부선KTX']]

      경부선KTX
2011   39060
2012   39896
2013   42005
2014   43621
2015   41702
2016   41266
2017   32427

In [20]:
#2011년데이터만 선택, loc사용

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B

In [28]:
# df.loc[:, ['name', 'age']]
df.loc['2011':'2011']

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B

In [21]:
#2013~2016년 행데이터 선택. loc사용

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A
2016   41266   10622    4984    3945    2395     A

In [29]:
df.loc['2013':'2016']

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2013   42005    6873    4088    1954     450     A
2014   43621    6626    4424    2244     560     A
2015   41702    8675    4606    3146    1300     A
2016   41266   10622    4984    3945    2395     A

In [22]:
#2012~2014년까지 경부선 KTX 컬럼만 조회. loc사용

      경부선KTX
2012   39896
2013   42005
2014   43621

In [30]:
df.loc['2012':'2014', ['경부선KTX']]

      경부선KTX
2012   39896
2013   42005
2014   43621

In [23]:
# loc 사용 안함

      경부선KTX
2012   39896
2013   42005
2014   43621

In [34]:
df['2012':'2015'][['경부선KTX']]

      경부선KTX
2012   39896
2013   42005
2014   43621
2015   41702

In [24]:
#2015~2017년까지 경부선KTX, 호남선KTX, 동해선KTX 컬럼 조회

      경부선KTX  호남선KTX  동해선KTX
2015   41702    8675    1300
2016   41266   10622    2395
2017   32427    9228    3786

In [35]:
df.loc['2015':'2017', ['경부선KTX', '호남선KTX', '동해선KTX']]

      경부선KTX  호남선KTX  동해선KTX
2015   41702    8675    1300
2016   41266   10622    2395
2017   32427    9228    3786

In [25]:
#isin 사용
#경부선등급이 'B','C'인 데이터 조회

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B
2012   39896    6967    4168    1771     350     B
2017   32427    9228    5570    5766    3786     C

In [42]:
# df['grade'].isin(['A'])
df.loc[df['경부선등급'].isin(['B', 'C'])]

      경부선KTX  호남선KTX  경전선KTX  전라선KTX  동해선KTX 경부선등급
2011   39060    7313    3627     309     300     B
2012   39896    6967    4168    1771     350     B
2017   32427    9228    5570    5766    3786     C

In [26]:
#위조건을 만족하는 경부선KTX 만 조회

      경부선KTX
2011   39060
2012   39896
2017   32427

In [43]:
df.loc[df['경부선등급'].isin(['B', 'C']), ['경부선KTX']]

      경부선KTX
2011   39060
2012   39896
2017   32427