In [1]:
import pandas as pd
df = pd.read_csv("../../data_set/2.데이터 클린징/group_sample.csv")
df

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m
4           5     B       65       80    90   w
5           6     B       98       89    50   m
6           7     B       45       90    80   m
7           8     B       25       78    90   w
8           9     C       15       98    20   w
9          10     C       45       93    50   w

In [2]:
df_class = df.groupby(['class'])
df_class

In [6]:
df_class.get_group(("A", ))

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m

In [8]:
df[ df['class'] == 'A' ]

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m

In [9]:
df_class.mean( numeric_only=True )

       student_no  science  english   math
class
A             2.5    61.50    94.75  46.25
B             6.5    58.25    84.25  77.50
C             9.5    30.00    95.50  35.00

In [10]:
df.groupby( ['class', 'sex'] ).mean(numeric_only=True)

           student_no  science  english  math
class sex
A     m           2.5     54.0     98.0  40.0
      w           2.5     69.0     91.5  52.5
B     m           6.5     71.5     89.5  65.0
      w           6.5     45.0     79.0  90.0
C     w           9.5     30.0     95.5  35.0

In [11]:
df_class.mean(numeric_only=True)[["math"]]

        math
class
A      46.25
B      77.50
C      35.00

In [12]:
df_class[['math']].mean()

        math
class
A      46.25
B      77.50
C      35.00

In [13]:
df_class['english'].count()

class
A    4
B    4
C    2
Name: english, dtype: int64

In [14]:
print(df_class[['english']].count())
print(df_class[['english']].sum())

       english
class
A            4
B            4
C            2
       english
class
A          379
B          337
C          191

In [15]:
df_class.agg({'math' : 'count', 'english' : 'sum'})

       math  english
class
A         4      379
B         4      337
C         2      191

In [16]:
df_class.agg({'math' : 'max', 'english' : 'min'})

       math  english
class
A        60       86
B        90       78
C        50       93

In [17]:
df_class.agg({'math' : ['max', 'min'], 'english' : 'min'})

      math     english
       max min     min
class
A       60  30      86
B       90  50      78
C       50  20      93

In [18]:
df_class.agg({'math' : ['max', 'min'], 'english' : ['min', 'sum']})

      math     english
       max min     min  sum
class
A       60  30      86  379
B       90  50      78  337
C       50  20      93  191

In [19]:
df_class.agg({'math' : ['max', 'min'], 'english' : ['min', 'sum']}).reset_index()

  class math     english
         max min     min  sum
0     A   60  30      86  379
1     B   90  50      78  337
2     C   50  20      93  191

In [20]:
df_class.agg({'math' : ['max', 'min'], 'english' : ['min', 'sum']}).reset_index(drop=True)

  math     english
   max min     min  sum
0   60  30      86  379
1   90  50      78  337
2   50  20      93  191