# Quiz
### 다음 데이터를 이용하여 데이터를 분석하시오
1. 도시별 가격 평균을 구하시오
2. 각 도시에서 과일별 가격 평균을 구하시오
3. 부산에서 가장 비싼 과일은 몇개인지 구하시오
4. 각 도시별로 가장 비싼 가격과 가장 적은 개수를 구하시오

In [1]:
import pandas as pd
df = pd.DataFrame({
    'city': ['부산', '부산', '부산', '부산', '서울', '서울', '서울'],
    'fruits': ['apple', 'orange', 'banana', 'banana', 'apple', 'apple', 'banana'],
    'price': [100, 200, 250, 300, 150, 200, 400],
    'quantity': [1, 2, 3, 4, 5, 6, 7]
})

In [2]:
# 1.도시별 가격 평균을 구하시오

      price  quantity
city
부산    212.5       2.5
서울    250.0       6.0

In [3]:
df_city = df.groupby(['city'])
df_city.mean(numeric_only=True)

      price  quantity
city
부산    212.5       2.5
서울    250.0       6.0

In [3]:
# 2.각 도시에서 과일별 가격 평균을 구하시오

             price  quantity
city fruits
부산   apple   100.0       1.0
     banana  275.0       3.5
     orange  200.0       2.0
서울   apple   175.0       5.5
     banana  400.0       7.0

In [4]:
df.groupby(['city', 'fruits']).mean(numeric_only=True)

             price  quantity
city fruits
부산   apple   100.0       1.0
     banana  275.0       3.5
     orange  200.0       2.0
서울   apple   175.0       5.5
     banana  400.0       7.0

In [4]:
# 3.부산에서 가장 비싼 과일은 몇개인지 구하시오

  city  fruits  price  quantity
3   부산  banana    300         4

In [14]:
df_city.get_group(('부산', )).max()
# df_class.mean(numeric_only=True)[["math"]]

city            부산
fruits      orange
price          300
quantity         4
dtype: object

In [5]:
# 4.각 도시별로 가장 비싼 가격과 가장 적은 개수를 구하시오

      price  quantity
city
부산      300         1
서울      400         5

In [15]:
df_city.agg({'price' : 'max', 'quantity' : 'min'})

      price  quantity
city
부산      300         1
서울      400         5